In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = [
    "I love machine learning",
    "One hot encoding is useful",
    "This is a simple example",
    "Python makes preprocessing easy",
    "Practice improves your skills"
]

In [3]:
sentences

['I love machine learning',
 'One hot encoding is useful',
 'This is a simple example',
 'Python makes preprocessing easy',
 'Practice improves your skills']

In [4]:
### Define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sentences]

In [6]:
one_hot_repr

[[3861, 8782, 2724, 738],
 [9016, 4603, 564, 3005, 9838],
 [8991, 3005, 9799, 7650, 4118],
 [8749, 4744, 4038, 309],
 [6572, 6832, 6760, 4521]]

In [16]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3861 8782 2724  738]
 [   0    0    0 9016 4603  564 3005 9838]
 [   0    0    0 8991 3005 9799 7650 4118]
 [   0    0    0    0 8749 4744 4038  309]
 [   0    0    0    0 6572 6832 6760 4521]]


In [10]:
## feature representation
dim = 10

In [21]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


array([[[-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04846656, -0.00670796,  0.00895729,  0.00320171,
         -0.02853166,  0.03777529,  0.02303895,  0.0207515 ,
         -0.02024739, -0.01584014],
        [-0.02464511,  0.01397158, -0.00945719, -0.03231321,
          0.02113244, -0.01512156,  0.04171597, -0.01321496,
         -0.03079853,  0.01352869],
        [-0.03381652,  0.03896074, -0.00251255,  0.0

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0, 3861, 8782, 2724,  738], dtype=int32)

In [40]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[[-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04318229,  0.01730731,  0.01227324, -0.026682  ,
          0.01557622,  0.03476099,  0.04879305,  0.02598295,
          0.00987409,  0.03644535],
        [-0.04846656, -0.00670796,  0.00895729,  0.00320171,
         -0.02853166,  0.03777529,  0.02303895,  0.0207515 ,
         -0.02024739, -0.01584014],
        [-0.02464511,  0.01397158, -0.00945719, -0.03231321,
          0.02113244, -0.01512156,  0.04171597, -0.01321496,
         -0.03079853,  0.01352869],
        [-0.03381652,  0.03896074, -0.00251255,  0.0