In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = [
    "I love machine learning",
    "One hot encoding is useful",
    "This is a simple example",
    "Python makes preprocessing easy",
    "Practice improves your skills"
]

In [3]:
sentences

['I love machine learning',
 'One hot encoding is useful',
 'This is a simple example',
 'Python makes preprocessing easy',
 'Practice improves your skills']

In [ ]:
### Define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sentences]

In [6]:
one_hot_repr

[[703, 6344, 5242, 4269],
 [1905, 9907, 2433, 9952, 2096],
 [7391, 9952, 5780, 3294, 657],
 [9111, 396, 6653, 5764],
 [1342, 5605, 4411, 3230]]

In [ ]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from keras.models import Sequential

In [9]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  703 6344 5242 4269]
 [   0    0    0 1905 9907 2433 9952 2096]
 [   0    0    0 7391 9952 5780 3294  657]
 [   0    0    0    0 9111  396 6653 5764]
 [   0    0    0    0 1342 5605 4411 3230]]


In [13]:
## feature representation
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/pravinmacm4/Documents/advanced-machine-learning-practice/krish_naik/complete-generative-ai-course-with-langchain-and-huggingface/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)